[workspace]
members = [
	"./codespan",
	"./codespan-reporting",
	"./codespan-lsp"
]
resolver = "3"
metadata.version_sync = true

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
